#! /bin/csh -f

# v0.3 Zerun Thu  9 Feb 11:22:55 CET 2023
#  - move the IHP_TECH and calibre runsets to setPDK.csh
# v1.0 Zerun Wed 31 Aug 10:46:52 CEST 2022\
#  - add layer props
#  - add read gds
# v0.1 - <kgf@iis.ee.ethz.ch> - Mon Nov  1 14:22:03 CET 2021
#  - copy from tsmc65 v0.1 

## set the relevant env for dfii and calibre
source ../.setPDK.csh

## Determine the tool to startup 
switch ($1)
  case 2021.3
     set CALIBRE = "calibre-2021.3 calibredrv -dl .init/ihpsg13.layerprops $argv[2-] "
     breaksw
  case xterm 
     set CALIBRE = "xterm" 
     breaksw
## this is the command that runs as default, it can be adjusted to whatever you
## please
default:
     set CALIBRE = "calibre-2021.3 calibredrv -dl .init/ihpsg13.layerprops $* "
     breaksw
endsw  

##echo "Starting $CALIBRE"
$CALIBRE
