
+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_verification/clk_rst_gen.sv

+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/tech_cells_generic/tc_sram.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/tech_cells_generic/tc_sram_impl.sv

+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/tech_cells_generic/tc_clk.sv

+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR
+incdir+/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/include
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/binary_to_gray.sv

+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR
+incdir+/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/include
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/cb_filter_pkg.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/cc_onehot.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/cdc_reset_ctrlr_pkg.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/cf_math_pkg.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/clk_int_div.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/credit_counter.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/delta_counter.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/ecc_pkg.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/edge_propagator_tx.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/exp_backoff.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/fifo_v3.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/gray_to_binary.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/heaviside.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/isochronous_4phase_handshake.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/isochronous_spill_register.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/lfsr.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/lfsr_16bit.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/lfsr_8bit.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/lossy_valid_to_stream.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/mv_filter.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/onehot_to_bin.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/plru_tree.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/passthrough_stream_fifo.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/popcount.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/ring_buffer.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/rr_arb_tree.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/rstgen_bypass.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/serial_deglitch.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/shift_reg.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/shift_reg_gated.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/spill_register_flushable.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/stream_demux.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/stream_filter.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/stream_fork.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/stream_intf.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/stream_join_dynamic.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/stream_mux.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/stream_throttle.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/sub_per_hash.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/sync.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/sync_wedge.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/unread.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/read.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/addr_decode_dync.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/boxcar.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/cdc_2phase.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/cdc_4phase.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/clk_int_div_static.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/trip_counter.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/addr_decode.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/addr_decode_napot.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/multiaddr_decode.sv

+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR
+incdir+/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/include
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/cb_filter.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/cdc_fifo_2phase.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/clk_mux_glitch_free.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/counter.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/ecc_decode.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/ecc_encode.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/edge_detect.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/lzc.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/max_counter.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/rstgen.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/spill_register.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/stream_delay.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/stream_fifo.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/stream_fork_dynamic.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/stream_join.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/cdc_reset_ctrlr.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/cdc_fifo_gray.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/fall_through_register.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/id_queue.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/stream_to_mem.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/stream_arbiter_flushable.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/stream_fifo_optimal_wrap.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/stream_register.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/stream_xbar.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/cdc_fifo_gray_clearable.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/cdc_2phase_clearable.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/mem_to_banks_detailed.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/stream_arbiter.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/stream_omega_net.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/mem_to_banks.sv

+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR
+incdir+/scratch/vlsi2_24fs26/reference_flow_copy/rtl/apb/include
+incdir+/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/include
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/apb/apb_pkg.sv

+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR
+incdir+/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/axi-4ecab47b5e77b28c/include
+incdir+/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/include
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/axi-4ecab47b5e77b28c/src/axi_pkg.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/axi-4ecab47b5e77b28c/src/axi_intf.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/axi-4ecab47b5e77b28c/src/axi_atop_filter.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/axi-4ecab47b5e77b28c/src/axi_burst_splitter_gran.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/axi-4ecab47b5e77b28c/src/axi_burst_unwrap.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/axi-4ecab47b5e77b28c/src/axi_bus_compare.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/axi-4ecab47b5e77b28c/src/axi_cdc_dst.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/axi-4ecab47b5e77b28c/src/axi_cdc_src.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/axi-4ecab47b5e77b28c/src/axi_cut.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/axi-4ecab47b5e77b28c/src/axi_delayer.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/axi-4ecab47b5e77b28c/src/axi_demux_simple.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/axi-4ecab47b5e77b28c/src/axi_dw_downsizer.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/axi-4ecab47b5e77b28c/src/axi_dw_upsizer.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/axi-4ecab47b5e77b28c/src/axi_fifo.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/axi-4ecab47b5e77b28c/src/axi_fifo_delay_dyn.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/axi-4ecab47b5e77b28c/src/axi_id_remap.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/axi-4ecab47b5e77b28c/src/axi_id_prepend.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/axi-4ecab47b5e77b28c/src/axi_inval_filter.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/axi-4ecab47b5e77b28c/src/axi_isolate.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/axi-4ecab47b5e77b28c/src/axi_join.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/axi-4ecab47b5e77b28c/src/axi_lite_demux.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/axi-4ecab47b5e77b28c/src/axi_lite_dw_converter.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/axi-4ecab47b5e77b28c/src/axi_lite_from_mem.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/axi-4ecab47b5e77b28c/src/axi_lite_join.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/axi-4ecab47b5e77b28c/src/axi_lite_lfsr.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/axi-4ecab47b5e77b28c/src/axi_lite_mailbox.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/axi-4ecab47b5e77b28c/src/axi_lite_mux.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/axi-4ecab47b5e77b28c/src/axi_lite_regs.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/axi-4ecab47b5e77b28c/src/axi_lite_to_apb.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/axi-4ecab47b5e77b28c/src/axi_lite_to_axi.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/axi-4ecab47b5e77b28c/src/axi_modify_address.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/axi-4ecab47b5e77b28c/src/axi_mux.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/axi-4ecab47b5e77b28c/src/axi_rw_join.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/axi-4ecab47b5e77b28c/src/axi_rw_split.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/axi-4ecab47b5e77b28c/src/axi_serializer.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/axi-4ecab47b5e77b28c/src/axi_slave_compare.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/axi-4ecab47b5e77b28c/src/axi_throttle.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/axi-4ecab47b5e77b28c/src/axi_to_detailed_mem.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/axi-4ecab47b5e77b28c/src/axi_burst_splitter.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/axi-4ecab47b5e77b28c/src/axi_cdc.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/axi-4ecab47b5e77b28c/src/axi_demux.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/axi-4ecab47b5e77b28c/src/axi_err_slv.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/axi-4ecab47b5e77b28c/src/axi_dw_converter.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/axi-4ecab47b5e77b28c/src/axi_from_mem.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/axi-4ecab47b5e77b28c/src/axi_id_serialize.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/axi-4ecab47b5e77b28c/src/axi_lfsr.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/axi-4ecab47b5e77b28c/src/axi_multicut.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/axi-4ecab47b5e77b28c/src/axi_to_axi_lite.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/axi-4ecab47b5e77b28c/src/axi_to_mem.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/axi-4ecab47b5e77b28c/src/axi_zero_mem.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/axi-4ecab47b5e77b28c/src/axi_interleaved_xbar.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/axi-4ecab47b5e77b28c/src/axi_iw_converter.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/axi-4ecab47b5e77b28c/src/axi_lite_xbar.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/axi-4ecab47b5e77b28c/src/axi_xbar_unmuxed.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/axi-4ecab47b5e77b28c/src/axi_to_mem_banked.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/axi-4ecab47b5e77b28c/src/axi_to_mem_interleaved.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/axi-4ecab47b5e77b28c/src/axi_to_mem_split.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/axi-4ecab47b5e77b28c/src/axi_xbar.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/axi-4ecab47b5e77b28c/src/axi_xp.sv

+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR
+incdir+/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/include
+incdir+/scratch/vlsi2_24fs26/reference_flow_copy/rtl/obi/include
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/obi/obi_pkg.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/obi/obi_intf.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/obi/obi_rready_converter.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/obi/apb_to_obi.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/obi/obi_to_apb.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/obi/obi_atop_resolver.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/obi/obi_cut.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/obi/obi_demux.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/obi/obi_err_sbr.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/obi/obi_mux.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/obi/obi_sram_shim.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/obi/obi_xbar.sv

+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR
+incdir+/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/axi-4ecab47b5e77b28c/include
+incdir+/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/register_interface-8146d26ca39e5d02/include
+incdir+/scratch/vlsi2_24fs26/reference_flow_copy/rtl/apb/include
+incdir+/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/include
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/register_interface-8146d26ca39e5d02/src/reg_intf.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/register_interface-8146d26ca39e5d02/vendor/lowrisc_opentitan/src/prim_subreg_arb.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/register_interface-8146d26ca39e5d02/vendor/lowrisc_opentitan/src/prim_subreg_ext.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/register_interface-8146d26ca39e5d02/src/apb_to_reg_v2.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/register_interface-8146d26ca39e5d02/src/axi_lite_to_reg.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/register_interface-8146d26ca39e5d02/src/axi_to_reg_v2.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/register_interface-8146d26ca39e5d02/src/periph_to_reg.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/register_interface-8146d26ca39e5d02/src/reg_cdc.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/register_interface-8146d26ca39e5d02/src/reg_cut.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/register_interface-8146d26ca39e5d02/src/reg_demux.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/register_interface-8146d26ca39e5d02/src/reg_err_slv.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/register_interface-8146d26ca39e5d02/src/reg_filter_empty_writes.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/register_interface-8146d26ca39e5d02/src/reg_mux.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/register_interface-8146d26ca39e5d02/src/reg_to_apb.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/register_interface-8146d26ca39e5d02/src/reg_to_mem.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/register_interface-8146d26ca39e5d02/src/reg_to_tlul.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/register_interface-8146d26ca39e5d02/src/reg_to_axi.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/register_interface-8146d26ca39e5d02/src/reg_uniform.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/register_interface-8146d26ca39e5d02/vendor/lowrisc_opentitan/src/prim_subreg_shadow.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/register_interface-8146d26ca39e5d02/vendor/lowrisc_opentitan/src/prim_subreg.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/register_interface-8146d26ca39e5d02/src/deprecated/apb_to_reg.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/register_interface-8146d26ca39e5d02/src/deprecated/axi_to_reg.sv

+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR
+incdir+/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/axi-4ecab47b5e77b28c/include
+incdir+/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/include
+incdir+/scratch/vlsi2_24fs26/reference_flow_copy/rtl/obi/include
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/axi_obi-7b5474ddc0a2b9f4/src/axi_to_detailed_mem_user.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/axi_obi-7b5474ddc0a2b9f4/src/axi_to_obi.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/axi_obi-7b5474ddc0a2b9f4/src/obi_to_axi.sv

+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR
+incdir+/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/include
+incdir+/scratch/vlsi2_24fs26/reference_flow_copy/rtl/cve2/include
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/cve2/cve2_pkg.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/cve2/cve2_alu.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/cve2/cve2_branch_predict.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/cve2/cve2_compressed_decoder.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/cve2/cve2_controller.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/cve2/cve2_counter.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/cve2/cve2_csr.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/cve2/cve2_decoder.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/cve2/cve2_fetch_fifo.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/cve2/cve2_load_store_unit.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/cve2/cve2_multdiv_fast.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/cve2/cve2_multdiv_slow.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/cve2/cve2_pmp.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/cve2/cve2_register_file_ff.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/cve2/cve2_wb.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/cve2/cve2_cs_registers.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/cve2/cve2_ex_block.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/cve2/cve2_id_stage.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/cve2/cve2_prefetch_buffer.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/cve2/cve2_if_stage.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/cve2/cve2_core.sv

+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR
+incdir+/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/axi-4ecab47b5e77b28c/include
+incdir+/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/register_interface-8146d26ca39e5d02/include
+incdir+/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/include
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/hyperbus-d20b59e5a581ace5/src/hyperbus_delay.sv

+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR
+incdir+/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/axi-4ecab47b5e77b28c/include
+incdir+/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/register_interface-8146d26ca39e5d02/include
+incdir+/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/include
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/hyperbus-d20b59e5a581ace5/src/hyperbus_tx_clk_delay.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/hyperbus-d20b59e5a581ace5/src/hyperbus_pkg.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/hyperbus-d20b59e5a581ace5/src/hyperbus_clk_gen.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/hyperbus-d20b59e5a581ace5/src/hyperbus_clock_diff_out.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/hyperbus-d20b59e5a581ace5/src/hyperbus_w2phy.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/hyperbus-d20b59e5a581ace5/src/hyperbus_phy2r.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/hyperbus-d20b59e5a581ace5/src/hyperbus_ddr_out.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/hyperbus-d20b59e5a581ace5/src/hyperbus_trx.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/hyperbus-d20b59e5a581ace5/src/hyperbus_cfg_regs.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/hyperbus-d20b59e5a581ace5/src/hyperbus_phy.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/hyperbus-d20b59e5a581ace5/src/hyperbus_phy_if.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/hyperbus-d20b59e5a581ace5/src/hyperbus_axi.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/hyperbus-d20b59e5a581ace5/src/hyperbus_frontend.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/hyperbus-d20b59e5a581ace5/src/hyperbus_async_bridge.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/hyperbus-d20b59e5a581ace5/src/hyperbus_iso_bridge.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/hyperbus-d20b59e5a581ace5/src/hyperbus_backend.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/hyperbus-d20b59e5a581ace5/src/hyperbus_synchronous.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/hyperbus-d20b59e5a581ace5/src/hyperbus_asynchronous.sv
/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/hyperbus-d20b59e5a581ace5/src/hyperbus_isochronous.sv

+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR
+incdir+/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/include
+incdir+/scratch/vlsi2_24fs26/reference_flow_copy/rtl/idma/include
+incdir+/scratch/vlsi2_24fs26/reference_flow_copy/rtl/obi/include
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/idma/idma_pkg.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/idma/idma_channel_coupler.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/idma/idma_dataflow_element.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/idma/idma_obi_read.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/idma/idma_obi_write.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/idma/idma_init_read.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/idma/idma_init_write.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/idma/idma_nd_midend.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/idma/idma_transfer_id_gen.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/idma/idma_legalizer_page_splitter.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/idma/idma_transport_layer_rw_obi.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/idma/idma_transport_layer_r_obi_w_init.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/idma/idma_legalizer_rw_obi.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/idma/idma_legalizer_r_obi_w_init.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/idma/idma_backend_rw_obi.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/idma/idma_backend_r_obi_w_init.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/idma/croc_idma.sv

+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR
+incdir+/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/include
+incdir+/scratch/vlsi2_24fs26/reference_flow_copy/rtl/obi/include
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/obi_uart/obi_uart_pkg.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/obi_uart/obi_uart_baudgen.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/obi_uart/obi_uart_interrupts.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/obi_uart/obi_uart_modem.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/obi_uart/obi_uart_rx.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/obi_uart/obi_uart_tx.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/obi_uart/obi_uart_register.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/obi_uart/obi_uart.sv

+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR
+incdir+/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/include
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/riscv-dbg/dm_pkg.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/riscv-dbg/debug_rom/debug_rom.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/riscv-dbg/debug_rom/debug_rom_one_scratch.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/riscv-dbg/dm_csrs.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/riscv-dbg/dm_mem.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/riscv-dbg/dmi_cdc.sv

+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR
+incdir+/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/include
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/riscv-dbg/dmi_jtag_tap.sv

+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR
+incdir+/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/include
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/riscv-dbg/dm_sba.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/riscv-dbg/dm_top.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/riscv-dbg/dmi_jtag.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/riscv-dbg/dm_obi_top.sv

+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR
+incdir+/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/include
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/riscv-dbg/tb/jtag_test_simple.sv

+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR
+incdir+/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/axi-4ecab47b5e77b28c/include
+incdir+/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/register_interface-8146d26ca39e5d02/include
+incdir+/scratch/vlsi2_24fs26/reference_flow_copy/rtl/apb/include
+incdir+/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/include
+incdir+/scratch/vlsi2_24fs26/reference_flow_copy/rtl/idma/include
+incdir+/scratch/vlsi2_24fs26/reference_flow_copy/rtl/obi/include
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/croc_pkg.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/user_pkg.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/soc_ctrl/soc_ctrl_regs_pkg.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/gpio/gpio_reg_pkg.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/clint/clint_reg_pkg.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/obi_timer/obi_timer_reg_pkg.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/neopixel/neopixel_pkg.sv

+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR
+incdir+/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/axi-4ecab47b5e77b28c/include
+incdir+/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/register_interface-8146d26ca39e5d02/include
+incdir+/scratch/vlsi2_24fs26/reference_flow_copy/rtl/apb/include
+incdir+/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/include
+incdir+/scratch/vlsi2_24fs26/reference_flow_copy/rtl/idma/include
+incdir+/scratch/vlsi2_24fs26/reference_flow_copy/rtl/obi/include
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/core_wrap.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/bootrom/bootrom.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/soc_ctrl/soc_ctrl_regs.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/gpio/gpio_reg_top.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/gpio/gpio.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/clint/clint.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/obi_timer/obi_timer.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/croc_domain.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/user_domain.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/neopixel/neopixel_reg.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/neopixel/write_to_fifo.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/neopixel/neopixel_dma.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/neopixel/neopixel_controller.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/neopixel/neopixel.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/croc_soc.sv

+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR
+incdir+/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/axi-4ecab47b5e77b28c/include
+incdir+/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/register_interface-8146d26ca39e5d02/include
+incdir+/scratch/vlsi2_24fs26/reference_flow_copy/rtl/apb/include
+incdir+/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/include
+incdir+/scratch/vlsi2_24fs26/reference_flow_copy/rtl/idma/include
+incdir+/scratch/vlsi2_24fs26/reference_flow_copy/rtl/obi/include
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/croc_chip.sv

+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR
+incdir+/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/axi-4ecab47b5e77b28c/include
+incdir+/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/register_interface-8146d26ca39e5d02/include
+incdir+/scratch/vlsi2_24fs26/reference_flow_copy/rtl/apb/include
+incdir+/scratch/vlsi2_24fs26/reference_flow_copy/rtl/common_cells/include
+incdir+/scratch/vlsi2_24fs26/reference_flow_copy/rtl/idma/include
+incdir+/scratch/vlsi2_24fs26/reference_flow_copy/rtl/obi/include
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/test/tb_croc_pkg.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/test/croc_vip.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/test/tb_croc_soc.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/test/tb_hyperbus_croc_soc.sv
/scratch/vlsi2_24fs26/reference_flow_copy/rtl/models/s27ks0641/s27ks0641.v

/scratch/vlsi2_24fs26/reference_flow_copy/.bender/git/checkouts/hyperbus-d20b59e5a581ace5/models/configurable_delay.behav.sv
../rtl/user_domain/user_rom.sv
